require 'json'

projects = JSON.parse(File.read("./static/projects.json"))
icons = JSON.parse(File.read("./static/icons.json"))
media = JSON.parse(File.read("./static/media.json"))

projects_array = []
icons_array = []
media_array = []

projects.each do |project|
  subs = []
  if project['sublinks']
    project['sublinks'].each do |link|
      subs.push("<a href=\"#{link['url']}\" target=\"_blank\">#{link['name']}</a>")
    end
  end
  projects_array.push("<span>- <a href=\"#{project['github']}\" target=\"_blank\">`#{project['name']}`</a> #{project['description']} #{subs.join(', ')}</span>")
end

icons.each do |icon|
  if icon["category"] == "language" or icon["category"] == "framework"
    icons_array.push("<img src=\"#{icon['icon']}\" alt=\"#{icon['name']}\" width=\"40\" height=\"40\">")
  end
end

media.each do |media_item|
  media_array.push("<a href=\"#{media_item['url']}\"><img src=\"#{media_item['icon']}\" alt=\"#{media_item['name']} logo\" width=\"40\" height=\"40\"></a>")
end

File.write("./README.md", <<~HEREDOC
  <!--AUTOGENERATED FILE-->
  Hi! I'm RaiderHCPlay — a student & self-taught dev coding in Neovim.
  ***

  
  ### 🎮 About Me

  Hey, I’m Paweł (aka RaiderHCPlay).  
  Web dev by day, anime and gaming enthusiast by night.  
  I experiment with Svelte, Ruby, and Rust, and do all my coding in Neovim. 
  I hope that Svelte will win one day... for my sanity. 

  <p align="left">
    <img src="https://img.shields.io/badge/Editor-Neovim-57A143?logo=neovim&logoColor=white" />
    <img src="https://img.shields.io/badge/Svelte%20Enjoyer-F73C00?logo=svelte&logoColor=white" />
    <img src="https://img.shields.io/badge/Arch%20Linux-1793D1?logo=archlinux&logoColor=white" />
  </p>

  ### 🚀Projects
  #{projects_array.join("\n\n")}
  ***
  ### 🛠️ Tech Stack
  #{icons_array.join(" ")}
  ***

  <details>
    <summary><b>Wakatime stats</b></summary>
    <a href="https://wakatime.com/@RaiderHCPlay"><img src="https://wakatime.com/share/@RaiderHCPlay/adf53bfd-d925-41d8-b6d5-9189284b7615.png" /></a>
  </details>

  ***

  ### 🌐 Media
  #{media_array.join(" ")}
HEREDOC
)

puts "Generated README"
