import icons from '../public/icons.json'
import projects from '../public/projects.json'
import { writeFile } from 'fs'

let projectsArray: string[] = []
let iconsArray: string[] = []

projects.map((project) => {
    projectsArray.push(
        `<span>- \`${project.name}\` ${project.description}</span>`
    )
})

icons.map((icon) => {
    iconsArray.push(
        `<img src=${icon.icon} alt=${icon.name} width="40" height="40">`
    )
})

writeFile(
    './README.md',
    `<!--AUTOGENERATED FILE-->
Hi! I'm RaiderHCPlay, a web developer.
***
### Projects

${projectsArray.join('\n\n')}
***
### Tech Stack

${iconsArray.join(' ')}
***

<details>
  <summary><b>Wakatime stats</b></summary>
  <a href="https://wakatime.com/@RaiderHCPlay" target="_blank"><img src="https://wakatime.com/share/@RaiderHCPlay/654097ea-4312-4b22-b6b8-fd416a885677.png"/></a>
</details>

***
### Media

<a href="https://discord.com/users/483660439633395724"><img src="https://cdn.simpleicons.org/discord/cba6f7" alt="Discord logo" width="40" height="40"></a>
	`,
    (err) => {
        if (err) console.log(err)
    }
)
