require 'json'

projects = JSON.parse(File.read("./static/projects.json"))
icons = JSON.parse(File.read("./static/icons.json"))

projects_array = []
icons_array = []

projects.each do |project|
  subs = []
  if project['sublinks']
    project['sublinks'].each do |link|
      subs.push("<a href=\"#{link['url']}\" target=\"_blank\">#{link['name']}</a>")
    end
  end
  projects_array.push("<span>- <a href=\"#{project['github']}\" target=\"_blank\">`#{project['name']}`</a> #{project['description']} #{subs.join(', ')}</span>")
end

icons.each do |icon|
  if icon["category"] == "language" or icon["category"] == "framework"
    icons_array.push("<img src=\"#{icon['icon']}\" alt=\"#{icon['name']}\" width=\"40\" height=\"40\">")
  end
end

File.write("./README.md", <<~HEREDOC
  <!--AUTOGENERATED FILE-->
  RaiderHCPlay — a student & self-taught dev coding in Neovim.
  ***

  
  ### 🎮 About Me

  Hey, I’m Paweł (aka RaiderHCPlay).  
  Web dev by day, anime and gaming enthusiast by night.  
  I experiment with Svelte, Ruby, and Rust, and do all my coding in Neovim.  
  I hope that Svelte will win one day... for my sanity. 

  <p align="left">
    <img src="https://img.shields.io/badge/Editor-Neovim-57A143?logo=neovim&logoColor=white" />
    <img src="https://img.shields.io/badge/Svelte%20Enjoyer-F73C00?logo=svelte&logoColor=white" />
    <img src="https://img.shields.io/badge/Arch%20Linux-1793D1?logo=archlinux&logoColor=white" />
    <img src="https://img.shields.io/badge/JJBA%20Crusader-c765be?logo=joplin&logoColor=white" />
  </p>

  ***

  ### 🚀 Projects
  #{projects_array.join("\n\n")}
  ***
  ### 🛠️ Tech Stack
  #{icons_array.join(" ")}
  ***

  ### 🌐 Media
  [![Discord](https://img.shields.io/badge/Discord-5865F2?style=for-the-badge&logo=discord&logoColor=white)](https://discord.com/users/483660439633395724)
[![WakaTime](https://img.shields.io/badge/WakaTime-000000?style=for-the-badge&logo=wakatime&logoColor=white)](https://wakatime.com/@RaiderHCPlay)

  HEREDOC
)

puts "Generated README"
